logger:
  default: info

  # ATTENTION
  # - If you comment out any logger, then you must also comment out the logs: node.
  #   Otherwise Home assistant will not start and the "check config" runs forever.
  # - If no logger is activated, remove the logs: node.
  # - Best solution: Localtuya is verbose, so keep this entry forever and forget the rest.
  logs:
    custom_components.localtuya.common: error

  
#    custom_components.automower: debug
#    homeassistant.components.device_tracker: debug

#    custom_components.localtuya: debug
#
#    custom_components.waste_at_bmv: debug
#
#    homeassistant.components.modbus: debug
#    pymodbus.client: debug
#
#    homeassistant.components.govee: debug
#    custom_components.govee: debug
#    govee_api_laggat: debug

#   Fritzbox
#    homeassistant.components.fritz: debug
#    fritzconnection: debug
#    fritzprofiles: debug

#    Homekit
#    homeassistant.components.homekit: debug
