# Configure a default set of integrations for Home Assistant to load
# see https://www.home-assistant.io/integrations/default_config/
default_config:

# Enable configuration through packages
homeassistant:
  packages: !include_dir_named packages/

media_player:
  - platform: enigma2
    host: 10.0.0.104
    mac_address: !secret vuplus_mac
    password: !secret vusolo4k_password
    name: "Vu+ Solo4K"
  - platform: samsungtv_tizen
    host: 10.0.0.103
    mac: !secret sasmsung_mac
    port: 8002
#    timeout: 30
#    protocol: ws
    api_key: !secret api_key
    device_id: !secret device_id
    source_list: '{"AV-Receiver": "KEY_HDMI1", "Receiver": "KEY_HDMI2", "Switch": "KEY_HDMI3", "Mac": "KEY_HDMI4"}'
    app_list: '{"Netflix": "11101200001/org.tizen.netflix-app", "Prime Video": "3201512006785/org.tizen.ignition", "YouTube": "111299001912", "Spotify": "3201606009684"}'

switch:
  - platform: wake_on_lan
    host: 10.0.0.102
    mac: !secret arbeitszimmer_mac
    name: "Arbeitszimmer"
  - platform: wake_on_lan
    host: 10.0.0.101
    mac: !secret diskstation_mac
    name: "Diskstation"

sensor:
  - platform: time_date
    display_options:
      - 'time'

logger:
  default: info
  logs:
    custom_components.waste_at_bmv: debug
    homeassistant.components.modbus: debug
    pymodbus.client: debug

logbook:
  exclude:
    entities:
      - automation.service_make_full_backup
      - device_tracker.christian_iphone
      - sensor.christian_activity
      - sensor.christian_average_active_pace
      - sensor.christian_battery_level
      - sensor.christian_battery_state
      - sensor.christian_bssid
      - sensor.christian_connection_type
      - sensor.christian_distance
      - sensor.christian_floors_ascended
      - sensor.christian_floors_descended
      - sensor.christian_geocoded_location
      - sensor.christian_last_update_trigger
      - sensor.christian_sim_1
      - sensor.christian_ssid
      - sensor.christian_steps
      - sensor.elias_iphone_activity
      - sensor.elias_iphone_average_active_pace
      - sensor.elias_iphone_battery_level
      - sensor.elias_iphone_battery_state
      - sensor.elias_iphone_bssid
      - sensor.elias_iphone_connection_type
      - sensor.elias_iphone_distance
      - sensor.elias_iphone_floors_ascended
      - sensor.elias_iphone_floors_descended
      - sensor.elias_iphone_geocoded_location
      - sensor.elias_iphone_last_update_trigger
      - sensor.elias_iphone_sim_1
      - sensor.elias_iphone_ssid
      - sensor.elias_iphone_steps
      - sensor.plug_wlan_anna_chain_of_lights_esphome_version
      - sensor.time
      - sun.sun
      - switch.plug_wlan_anna_chain_of_lights_reboot
      - switch.switch_wlan_elias_light_reboot

history:
  exclude:
    entities:
      - automation.service_make_full_backup
      - light.plug_wlan_anna_chain_of_lights_blue_led
      - light.plug_wlan_anna_chain_of_lights_red_led
      - light.wohnzimmer
      - persistent_notification.config_entry_discovery
      - sensor.battery_level
      - sensor.battery_state
      - sensor.bssid
      - sensor.christian_activity
      - sensor.christian_average_active_pace
      - sensor.christian_battery_level
      - sensor.christian_battery_state
      - sensor.christian_bssid
      - sensor.christian_connection_type
      - sensor.christian_distance
      - sensor.christian_floors_ascended
      - sensor.christian_floors_descended
      - sensor.christian_last_update_trigger
      - sensor.christian_sim_1
      - sensor.christian_ssid
      - sensor.christian_steps
      - sensor.elias_iphone_activity
      - sensor.elias_iphone_average_active_pace
      - sensor.elias_iphone_battery_level
      - sensor.elias_iphone_battery_state
      - sensor.elias_iphone_bssid
      - sensor.elias_iphone_connection_type
      - sensor.elias_iphone_distance
      - sensor.elias_iphone_floors_ascended
      - sensor.elias_iphone_floors_descended
      - sensor.elias_iphone_geocoded_location
      - sensor.elias_iphone_last_update_trigger
      - sensor.elias_iphone_sim_1
      - sensor.elias_iphone_ssid
      - sensor.elias_iphone_steps
      - sensor.geocoded_location
      - sensor.last_update_trigger
      - sensor.plug_wlan_anna_chain_of_lights_esphome_version
      - sensor.sim_1
      - sensor.ssid
      - sensor.time
      - switch.elias_light_reboot
      - switch.plug_wlan_anna_chain_of_lights_reboot
      - switch.switch_wlan_elias_light_reboot

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
