# Name: LoraTop Tuya Smart Life Wifi Light Switch
# Link to device: http://de.aliexpress.com/item/4000202499821.html
# Switch pins must be isolated (no 220V).
#
# Flashed with Tuya-Convert, see
# - https://www.youtube.com/watch?v=dt5-iZc4_qU
# - https://www.heise.de/ct/artikel/Tuya-Convert-IoT-Geraete-ohne-Loeten-vom-Cloud-Zwang-befreien-4283623.html
#
# Link for GPIO layout: https://de.ibn.by/2020/02/25/dee-esp-module/
#
# GPIO  Mode  Done Description
#  0    out   x    Red LED (1 – on, 0 – off)
#  4    in    x    Switch (1 – released, 0 – pressed)
# 12    in    -    Pairing button (1 – released, 0 – pressed) - no functionality
# 13    out   x    Relay (0 – open, 1 – close)
# 16    out   -    Blue LED (1 – off, 0 – on) - no functionality


substitutions:
  device_name: elias-light                                                # Device name, prefix for all sub-componentes
  device_friendly_name: Elias Light                                       # Must be the same as device name, but in a better readable form
  device_description: Licht Zimmer Elias                                  # Description for device web page
  ip_adress: 10.0.0.200                                                   # IP adress

esphome:
  name: ${device_name}
  comment: ${device_description}
  friendly_name: ${device_friendly_name}

esp8266:
  board: esp01_1m

# Network settings
packages:
  wifi: !include .network.yaml

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO13
    id: relay1

light:
  - platform: binary
    id: light1
    name: None
    output: relay1
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: switch1
    name: "Switch"
    on_press:
      then:
        - light.toggle: light1
    internal: True

status_led:
  pin: GPIO0
