# Name: Jules V
# Energy Monitoring Smart Plug with button, blue and red LED.

substitutions:
  device_name: plug_wlan_anna_chain_of_lights
  device_description: Zimmer Anna-Mavie Lichterkette
  friendly_name: Plug Wlan Anna Chain Of Lights
  short_name: Anna Chain Of Lights
  ip_adress: 10.0.0.201

<<: !include .yules.yaml
